name: "Workflow Commands"

on:
    push:
        branches:
            - main

jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: Group related log messages
              run: |
                echo "::group::My Grouped Messages"
                echo "Message 1"
                echo "Message 2"
                echo "::endgroup::"